#!/bin/sh

##
# name: pre-push
# author: Marnix Harderwijk
# description: setup git hook for a pre push
##

##
# define echo colors
##
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

##
# start yarn build and check for approval on to push
##
yarn build
if [ $? -eq 0 ]; then
  echo "${GREEN}√${NC} build successful..."
  echo "${GREEN}-->${NC} Thumbs up! Approving push..."
  exit 0
else
  echo "${RED}Error:${NC} build failed..."
  echo "${RED}-->${NC} Please check the code and/or build output for errors..."
  echo "${RED}-->${NC} Rejecting push..."
  exit 1
fi
